services:
    logstash:
      image: logstash:7.17.9
      depends_on:
        - elasticsearch
      environment:
        XPACK_MONITORING_ENABLED: "false"
        ES_HOST: "elasticsearch:9200"
      ports:
        - "5044:5044/udp"
      volumes:
        - ./logstash/logstash.conf:/config/logstash.conf:ro
      command: logstash -f /config/logstash.conf

    elasticsearch:
      image: elasticsearch:7.17.9
      environment:
        discovery.type: single-node
      ports:
        - 9201:9200
      volumes:
        - /tmp/esdata:/tmp/elasticsearch/data

    kibana:
      image: kibana:7.17.9
      environment:
        enterpriseSearch.host: 'http://elasticsearch:9200'
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
