version: '3.8'
services:
  auth_nginx:
    image: nginx:1.23
    env_file:
      - .env-sample
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/auth_service:/etc/nginx/conf.d:ro
    depends_on:
      - auth_db
      - auth_redis
      - auth_service
    ports:
      - '${AUTH_NGINX_PUBLIC_PORT}:${AUTH_NGINX_PORT}'
  auth_db:
    image: postgres:14
    container_name: auth_database
    env_file:
      - "./flask_app/.env"
    expose:
      - '${DB_PORT}'
    volumes:
      - auth_database:/var/lib/postgresql/data/
    
  auth_redis:
    image: redis:7.0.5
    container_name: auth_redis
    env_file:
      - "./flask_app/.env"
    expose:
      - '${REDIS_PORT}'
        
  auth_service:
    build: ./flask_app
    container_name: auth_server
    command: gunicorn --bind '${AUTH_SERVER_HOST}:${AUTH_SERVER_PORT}' wsgi_app:app
    env_file:
      - "./flask_app/.env"
    expose:
      - '${AUTH_SERVER_PORT}'

volumes:
  auth_database:
