version: '3.8'
services:
  auth_nginx:
    image: nginx:1.23
    env_file:
      - "./flask_app/.env"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/auth_service:/etc/nginx/conf.d:ro
    depends_on:
      - auth_redis
      - auth_service
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://${LOGSTASH_PUBLIC_HOST}:${LOGSTASH_PUBLIC_PORT}'
        tag: auth-nginx
    ports:
      - '${AUTH_NGINX_PUBLIC_PORT}:${AUTH_NGINX_PORT}'
    
  auth_redis:
    image: redis:7.0.5
    container_name: auth_redis
    env_file:
      - "./flask_app/.env"
    expose:
      - '${REDIS_PORT}'
        
  auth_service:
    build: ./flask_app
    container_name: auth_server
    command: gunicorn --bind '${AUTH_SERVER_HOST}:${AUTH_SERVER_PORT}' wsgi_app:app
    env_file:
      - "./flask_app/.env"
    expose:
      - '${AUTH_SERVER_PORT}'

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger_auth
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
    restart: unless-stopped

  auth_db:
    image: postgres:14
    container_name: auth_database
    env_file:
      - "./flask_app/.env"
    expose:
      - '${DB_PORT}'
