version: '3.8'
services:
  auth_db:
    image: postgres:14
    container_name: auth_database
    env_file:
      - "./flask_app/.env"
    expose:
      - '${DB_PORT}'
    volumes:
      - auth_database:/var/lib/postgresql/data/
    
  auth_redis:
    image: redis:7.0.5
    container_name: auth_redis
    env_file:
      - "./flask_app/.env"
    expose:
      - '${REDIS_PORT}'
        
  auth_service:
    build: ./flask_app
    container_name: auth_server
    command: gunicorn --bind '${AUTH_SERVER_HOST}:${AUTH_SERVER_PORT}' wsgi_app:app
    env_file:
      - "./flask_app/.env"
    ports:
      - '${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}'

volumes:
  auth_database:
