services:

  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env

  promoapp:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: tests
    env_file:
      - ./promocode_service/promocode_service/.env
    volumes:
      - app_volume:/home/promo/web
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - celery

  redis:
    image: redis:7-alpine

  celery:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: celery-prod
    env_file:
      - ./promocode_service/promocode_service/.env
    volumes:
      - app_volume:/home/promo/web
    depends_on:
      - redis
      - postgres
  
  celery-beat:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: celery-prod
    env_file:
      - ./promocode_service/promocode_service/.env
    volumes:
      - app_volume:/home/promo/web
    depends_on:
      - redis
      - postgres
  
  dashboard:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: celery-prod
    env_file:
      - ./promocode_service/promocode_service/.env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - postgres
      - celery

volumes:
  postgres_data:
  app_volume:
