services:

  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env

  promoapp:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: prod
    volumes:
      - app_volume:/home/promo/web
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine

  celery:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: celery-prod
    volumes:
      - app_volume:/home/promo/web
    depends_on:
      - redis
      - postgres
  
  celery-beat:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: celery-beat-prod
    volumes:
      - app_volume:/home/promo/web
    depends_on:
      - redis
      - postgres
  
  dashboard:
    build:
      context: ./promocode_service
      dockerfile: Dockerfile
      target: flower-prod
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - app_volume:/data:ro
    depends_on:
      - promoapp
    ports:
      - "8089:80"

volumes:
  postgres_data:
  app_volume:
