# Generated by Django 3.2 on 2023-03-12 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTemplate',
            fields=[
                ('slug', models.SlugField(help_text='Слаг, который будет идентифицировать конкретный шаблон', primary_key=True, serialize=False, verbose_name='Тип шаблона')),
                ('description', models.CharField(max_length=250, verbose_name='Описание шаблона')),
                ('template', models.TextField(help_text='Текст шаблона общей рассылки. html страница с общей информацией или просто текст.', validators=[django.core.validators.RegexValidator(message='Необходимо ввести валидный html текст или просто строку без тэгов', regex='^<.*>.*</.*>$|^[^<>/]+$')], verbose_name='Текст шаблона')),
            ],
            options={
                'verbose_name': 'Общий шаблон',
                'verbose_name_plural': 'Общие шаблоны',
            },
        ),
        migrations.CreateModel(
            name='PersonalizedTemplate',
            fields=[
                ('slug', models.SlugField(help_text='Слаг, который будет идентифицировать конкретный шаблон', primary_key=True, serialize=False, verbose_name='Тип шаблона')),
                ('description', models.CharField(max_length=250, verbose_name='Описание шаблона')),
                ('template', models.TextField(help_text='Текст персонализированного шаблона. Возможно использовать внутри следующие вставки: {{ user '
                  '}}, {{ film }}', validators=[django.core.validators.RegexValidator(message='Необходимо ввести валидный html текст или просто строку без тэгов', regex='^<.*>.*</.*>$|^[^<>/]+$')], verbose_name='Текст шаблона')),
            ],
            options={
                'verbose_name': 'Персонализированный шаблон',
                'verbose_name_plural': 'Персонализированные шаблоны',
            },
        ),
    ]
