version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  ugc_etl:
    build:
      context: ./ugc_etl/etl
      dockerfile: Dockerfile
    image: ugc_etl_image
    depends_on:
      - redis-state-storage
      - kafka-broker
      - clickhouse-node1
    env_file:
      - .ugc.env

volumes:
  mongodb_data_container:
