services:
  rabbitmq:
    image: rabbitmq:3.11.10-management-alpine
    env_file:
      - ./rabbitmq/.env.example
    ports:
      - 15672:15672
      - 5672:5672
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025