services:
  rabbitmq:
    image: rabbitmq:3.11.10-management-alpine
    container_name: rabbitmq-container
    env_file:
      - ./rabbitmq/.env.example
    ports:
      - 15672:15672
      - 5672:5672
      
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog-container
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  sender:
    build: ./sender_worker
    image: sender-worker
    container_name: sender-worker-container
    env_file:
      - ./sender_worker/.env.dev
    command: python /home/sender/main.py
    restart: on-failure
    depends_on:
      - mailhog
      - rabbitmq

  etl_worker:
    build:
      context: ./etl_worker
      dockerfile: Dockerfile
    env_file:
      - ./etl_worker/.env
    depends_on:
      - rabbitmq

  notification_admin:
    build: ./django
    ports:
      - 8000:8000
    image: notification_admin_app
    volumes:
      - static_volume:/admin_panel/files
    container_name: notification_admin_container
    env_file:
      - ./django/config/.env

  volumes:
  - static_volume