"""user_access_history_action

Revision ID: 19c551ddaccb
Revises: 138ca0a2b975
Create Date: 2023-01-27 15:09:43.678364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19c551ddaccb'
down_revision = '138ca0a2b975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    action = postgresql.ENUM('LOGIN', 'LOGOUT', 'REFRESH_TOKEN', 'LOGIN_HISTORY', 'CHANGE_CREDITS', name='action')
    action.create(op.get_bind())
    op.add_column('user_access_history', sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'REFRESH_TOKEN', 'LOGIN_HISTORY', 'CHANGE_CREDITS', name='action'), nullable=False))
    op.alter_column('user_access_history', 'device',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_access_history', 'action')
    action = postgresql.ENUM('LOGIN', 'LOGOUT', 'REFRESH_TOKEN', 'LOGIN_HISTORY', 'CHANGE_CREDITS', name='action')
    action.drop(op.get_bind())
    # ### end Alembic commands ###
