"""user_access_history_action

Revision ID: 45e94b22a893
Revises: 138ca0a2b975
Create Date: 2023-01-27 15:05:59.768655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e94b22a893'
down_revision = '138ca0a2b975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access_history', sa.Column('action', sa.String(), nullable=False))
    op.alter_column('user_access_history', 'device',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_access_history', 'device',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_access_history', 'action')
    # ### end Alembic commands ###
