"""Add (first,last) name

Revision ID: 897dfea3c5d9
Revises: b128430e7a88
Create Date: 2023-03-13 21:53:23.289707

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "897dfea3c5d9"
down_revision = "b128430e7a88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_user_access_history_id", "user_access_history", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_user_access_history_id"), "user_access_history", ["id"]
    )
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_constraint(
        op.f("uq_user_access_history_id"), "user_access_history", type_="unique"
    )
    op.create_unique_constraint(
        "uq_user_access_history_id", "user_access_history", ["id", "device"]
    )
    # ### end Alembic commands ###
