"""Add column third_party_id to users

Revision ID: ed36717f9ace
Revises: d997da871fed
Create Date: 2023-01-25 15:55:35.418747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed36717f9ace'
down_revision = 'd997da871fed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_id'), 'roles', ['id'])
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    op.create_unique_constraint(op.f('uq_user_access_history_id'), 'user_access_history', ['id'])
    op.create_unique_constraint(op.f('uq_user_roles_user_id'), 'user_roles', ['user_id'])
    op.add_column('users', sa.Column('third_party_id', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'third_party_id')
    op.drop_constraint(op.f('uq_user_roles_user_id'), 'user_roles', type_='unique')
    op.drop_constraint(op.f('uq_user_access_history_id'), 'user_access_history', type_='unique')
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_constraint(op.f('uq_roles_id'), 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    # ### end Alembic commands ###
