# Generated by Django 4.1.7 on 2023-03-25 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "promo_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("promo_value", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField()),
                ("is_reusable", models.BooleanField()),
                ("activate_until", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PromocodeType",
            fields=[
                (
                    "type_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PromocodeUserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField()),
                (
                    "promo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promocode.promocode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="promocode",
            name="type_of_promocode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="promocode.promocodetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocodeuserhistory",
            constraint=models.UniqueConstraint(
                fields=("promo_id", "user_id"), name="unique pair promocode-user"
            ),
        ),
    ]
