# Generated by Django 4.1.7 on 2023-03-29 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import promocode.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "promo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "promo_value",
                    models.CharField(
                        default=promocode.models.get_promo_code,
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="promo value",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("is_valid", models.BooleanField(verbose_name="is valid")),
                ("number_activations", models.PositiveIntegerField(default=0)),
                ("personal_user_id", models.UUIDField(null=True)),
                ("activate_until", models.DateTimeField(verbose_name="activate until")),
            ],
            options={
                "verbose_name": "promocode",
                "verbose_name_plural": "promocodes",
                "db_table": "promocode",
            },
        ),
        migrations.CreateModel(
            name="PromocodeType",
            fields=[
                (
                    "type_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                ("max_number_activation", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "promocode type",
                "verbose_name_plural": "promocode type",
                "db_table": "promocode_type",
            },
        ),
        migrations.CreateModel(
            name="PromocodeUserHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField()),
                (
                    "promo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promocode.promocode",
                    ),
                ),
            ],
            options={
                "verbose_name": "promocode history",
                "verbose_name_plural": "promocode history",
                "db_table": "promocode_user_history",
            },
        ),
        migrations.AddField(
            model_name="promocode",
            name="type_of_promocode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="promocode.promocodetype",
                verbose_name="type of promocode",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocodeuserhistory",
            constraint=models.UniqueConstraint(
                fields=("promo_id", "user_id"), name="unique pair promocode-user"
            ),
        ),
    ]
