# Generated by Django 4.1.7 on 2023-03-28 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promocode", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={"verbose_name": "promocode", "verbose_name_plural": "promocodes"},
        ),
        migrations.AlterModelOptions(
            name="promocodetype",
            options={
                "verbose_name": "promocode type",
                "verbose_name_plural": "promocode type",
            },
        ),
        migrations.AlterModelOptions(
            name="promocodeuserhistory",
            options={
                "verbose_name": "promocode history",
                "verbose_name_plural": "promocode history",
            },
        ),
    ]
