# Generated by Django 4.1.7 on 2023-03-29 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("promocode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="number_activations",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="personal_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="promo_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="promocodetype",
            name="type_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
