# Generated by Django 4.1.7 on 2023-03-29 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "promocode",
            "0002_alter_promocode_options_alter_promocodetype_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="activate_until",
            field=models.DateTimeField(verbose_name="activate until"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_reusable",
            field=models.BooleanField(verbose_name="is reusable"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_valid",
            field=models.BooleanField(verbose_name="is valid"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="promo_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="promo_value",
            field=models.CharField(max_length=20, verbose_name="promo value"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="type_of_promocode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="promocode.promocodetype",
                verbose_name="type of promocode",
            ),
        ),
        migrations.AlterField(
            model_name="promocodeuserhistory",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
