# Generated by Django 4.1.7 on 2023-03-29 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promocode", "0003_alter_promocode_activate_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="promo_value",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(8)],
                verbose_name="promo value",
            ),
        ),
    ]
