# Generated by Django 4.1.7 on 2023-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promocode", "0003_alter_promocode_number_activations_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="promocodeuserhistory",
            name="unique pair promocode-user",
        ),
        migrations.RenameField(
            model_name="promocode",
            old_name="promo_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="promocode",
            old_name="type_of_promocode",
            new_name="promocode_type_id",
        ),
        migrations.RenameField(
            model_name="promocodetype",
            old_name="type_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="promocodeuserhistory",
            old_name="promo_id",
            new_name="promocode_id",
        ),
        migrations.AddConstraint(
            model_name="promocodeuserhistory",
            constraint=models.UniqueConstraint(
                fields=("promocode_id", "user_id"), name="unique pair promocode-user"
            ),
        ),
    ]
