# Generated by Django 4.1.7 on 2023-04-05 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "promocode",
            "0004_remove_promocodeuserhistory_unique pair promocode-user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocodeuserhistory",
            name="expire_at",
        ),
    ]
