# Generated by Django 4.1.7 on 2023-04-06 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "promocode",
            "0006_remove_task_api_endpoint_task_notify_api_endpoint_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="promocode",
            old_name="promocode_type_id",
            new_name="promocode_type",
        ),
    ]
