# Generated by Django 4.1.7 on 2023-04-06 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promocode", "0007_rename_promocode_type_id_promocode_promocode_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promocodeuserhistory",
            old_name="promocode_id",
            new_name="promocode",
        ),
    ]
